    # ansible requires epel-release
    - name: "Install ansible"
      yum:
        name: "{{ packages }}"
        state: "present"
      vars:
        packages:
          - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

    - name: "Install ansible"
      yum:
        name: "ansible"
        state: "present"
